spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3307/springcloud_sell?characterEncoding=utf-8&useSSL=false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
